jobs:
  - name: build-pack-and-publish
    plan:
      - put: version
        params: {bump: patch}
      - get: source-code
        trigger: true
      - task: compile-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotaleducation/boot-build
          inputs:
            - name: source-code
          run:
            path: sh
            args:
              - -exc
              - |
                cd source-code

                service postgresql start

                sudo -u postgres psql -f databases/tracker/create_databases.sql
                flyway -url="jdbc:postgresql://localhost:5432/tracker_test" -locations=filesystem:databases/tracker migrate -user=tracker -password=password

                ./gradlew test
      - task: pack-and-publish
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: pivotaleducation/pack-and-publish
          inputs:
            - name: source-code
            - name: version
          run:
            path: bash
            args:
              - -exc
              - |
                source /opt/resource/common.sh
                start_docker "5" "5" "" ""

                BUILD_NUMBER=`cat version/number`

                cd source-code
                ./gradlew bootBuildImage --imageName=((DOCKER_HUB_USERNAME))/pal-tracker:build-${BUILD_NUMBER}
                docker login -u ((DOCKER_HUB_USERNAME)) -p ((DOCKER_HUB_PASSWORD))
                docker push ((DOCKER_HUB_USERNAME))/pal-tracker:build-${BUILD_NUMBER}
  - name: migrate-review-db
    plan:
      - get: source-code
        trigger: true
        passed:
          - build-pack-and-publish
      - get: version
        passed:
          - build-pack-and-publish
      - task: migrate-db
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotaleducation/boot-build
          inputs:
            - name: source-code
            - name: version
          run:
            path: bash
            args:
              - -exc
              - |
                  cd source-code
                  flyway -url="jdbc:postgresql://((REVIEW_DB_SERVER))/((REVIEW_DB_NAME))" -locations=filesystem:databases/tracker clean migrate -user=((REVIEW_DB_USER)) -password='((REVIEW_DB_PASSWORD))'
  - name: deploy-to-review
    plan:
      - get: source-code
        trigger: true
        passed:
        - build-pack-and-publish
      - get: version
        passed:
        - build-pack-and-publish
        - migrate-review-db
      - task: deploy-to-review
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotaleducation/deploy-gke
          inputs:
            - name: source-code
            - name: version
          run:
            path: sh
            args:
              - -exc
              - |
                printf '%s' '((GCP_SERVICE_KEY_JSON))' > google-key.json
                gcloud auth activate-service-account --key-file="google-key.json"
                gcloud container clusters get-credentials ((K8S_CLUSTER_NAME)) --project ((GCP_PROJECT_NAME)) --zone us-central1-c

                BUILD_NUMBER=`cat version/number`

                grep "concourse.run_number" source-code/k8s/environments/review/deployment.yaml
                sed -i "s/concourse.run_number/${BUILD_NUMBER}/g" source-code/k8s/environments/review/deployment.yaml
                kubectl apply -k source-code/k8s/environments/review
  - name: deploy-to-production
    plan:
      - get: source-code
        passed:
          - deploy-to-review
      - get: version
        passed:
          - deploy-to-review
      - task: deploy-to-production
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotaleducation/deploy-gke
          inputs:
            - name: source-code
            - name: version
          run:
            path: sh
            args:
              - -exc
              - |
                printf '%s' '((GCP_SERVICE_KEY_JSON))' > google-key.json
                gcloud auth activate-service-account --key-file="google-key.json"
                gcloud container clusters get-credentials ((K8S_CLUSTER_NAME)) --project ((GCP_PROJECT_NAME)) --zone us-central1-c

                BUILD_NUMBER=`cat version/number`

                grep "concourse.run_number" source-code/k8s/environments/production/deployment.yaml
                sed -i "s/concourse.run_number/${BUILD_NUMBER}/g" source-code/k8s/environments/production/deployment.yaml
                kubectl apply -k source-code/k8s/environments/production
resources:
  - name: source-code
    type: git
    source:
      uri: https://((GITHUB_USERNAME)):((GITHUB_PASSWORD))@github.com/((GITHUB_USERNAME))/pal-tracker.git
      branch: main
  - name: version
    type: semver
    source:
      initial_version: "0.0.1"
      driver: git
      uri: https://((GITHUB_USERNAME)):((GITHUB_PASSWORD))@github.com/((GITHUB_USERNAME))/pal-tracker.git
      branch: build
      file: number
      username: ((GITHUB_USERNAME))
      password: ((GITHUB_PASSWORD))
