apiVersion: v1
kind: ConfigMap
metadata:
  name: pal-tracker
  labels:
    app: pal-tracker
data:
  welcome.message: "i love k8s"
  management.endpoints.web.exposure.include: "info,health,palTrackerFailure"
